import Head from "next/head";
import { DataProvider } from "~/components/DataProvider";
import { Form } from "~/components/Form";
import Header from "~/components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Form />
    </>
  );
}
